export default {
    welcomeMessage: 'Welcome, Client Name',
    active_language: 'ACTIVE LANGUAGE',
    dashboard: 'Dashboard',
    profile: 'Profile',
    tickets: 'Tickets',
    invoices: 'Invoices',
    services: 'Services',
    team: 'Team',
    see_all_tickets: 'See all tickets',
    ticket_number: 'Ticket Number',
    title: 'Title',
    date: 'Date',
    type: 'Type',
    priority: 'Priority',
    status: 'Status',
    language: 'Active Language',
    signOut: 'Sign Out',
    my_tenant: 'My Tenant',
    organization_information: 'Organization Information',
    invoices_page: 'Your invoices,sir',
    services_no_way: 'Services, no way',
    token: 'TOKEN',
    active_relation: 'Active Relation',
    permissions: 'Permissions',
    search: 'Search',
    showOpenTickets: 'Show Open Tickets',
    showAll: 'Show All',
    createTicket: 'Create Ticket',
    createNewTicket: 'Create New Ticket',
    cancel:'Cancel',
    create : 'Create',
    date_time_created: 'Date/Time Created',
    created: 'Created',
    description: 'Description',
    random_description: 'Random Description',
    add_comments: 'Add Comments',
    send: 'Send',
    comment_added: 'Comment added successfully!',
    information:'Information',
    attachments: 'Attachments'

    // other English translations...
}
